### ISSUE TITLE
talk to Kelso about minimal viable QGIS <-> GeoJSON properties table

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#118]
cc @nvkelso

**Comment by thisisaaronland** [comment]
Is there an equivalent to BCP-47 for ogr2ogr / Shapefile conventions?

https://github.com/whosonfirst/whosonfirst-names#rfc-5646-bcp-47-comformance

**Comment by thisisaaronland** [comment]
cc @stepps00

**Comment by nvkelso** [comment]
QGIS can edit GeoJSON files natively, so I'm not sure there is an issue to fix?

Shapefiles do suffer from 10 char length field names and use of `_` instead of `:`, etc. I've setup a "slim" mode that converts longer WOF field names to SHP safe names here: https://github.com/whosonfirst/py-mapzen-whosonfirst-utils/blob/master/scripts/wof-csv-to-feature-collection#L55-L112.
