### ISSUE TITLE
PIP lookups for venues scoped to... venues

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#149]
This will always fail. For example ID `588371405` 

![screen shot 2016-07-29 at 07 40 38](https://cloud.githubusercontent.com/assets/12658759/17252034/dc0fc098-555f-11e6-9b1d-9e87c02e934b.png)

**Comment by dphiffer** [comment]
Yeah, this struck me as odd too. Turns out that I'm using the placetype as [a reference point](https://github.com/whosonfirst/py-mapzen-whosonfirst-pip-utils/blob/dphiffer/boundary-issues/mapzen/whosonfirst/pip/utils/__init__.py#L54-L64) to figure out what the parent types are, so I think I do actually want to pass it for looking up venue hierarchies.
