### ISSUE TITLE
Public Site?

### ISSUE THREAD

**Issue by davidbarratt** [whosonfirst/whosonfirst-www-boundaryissues#199]
Does a publicly hosted version of this exist somewhere?

If not, I think it would be great if it would let you login with your GitHub account, then create a fork of the who's on first data repo, allow you to edit it (committing changes to your fork) and then submit a PR to the upstream repo.

Is something like this on the roadmap already?

**Comment by thisisaaronland** [comment]
We don't have any plans in the short-term for this kind of public access, but it's an intriguing idea.

Getting input and participation from (not-staff) is definitely a goal but right now we've just been focused on getting the basic scaffolding up and running. It is possible – not necessarily "easy" yet – to run the entire BI stack on a Vagrant machine.

That's mostly been for internal development but now that someone (else) has expressed interest we will start to think about cleaning it up enough that you shouldn't have to be staff to use it. That would be the first step.

The second step would be to update the code to be smart about forks and PRs. There are already preliminary hooks in BI for branches so it shouldn't be _too_ hard (famous last words :-)

So not quite what you're asking for and not quite as soon as anyone might like but we'll add it to the list.

**Comment by thisisaaronland** [comment]
Related: https://github.com/whosonfirst/vagrant-whosonfirst-www-boundaryissues

I will let @dphiffer chime in on how closely that has tracked recent changes (to the code base).

**Comment by davidbarratt** [comment]
Great! Thanks for the update!

**Comment by davidbarratt** [comment]
The reason I was asking, was because the boundaries for my neighborhood are wrong and I was looking for an "easy" way to fix it. I want to start using this data in an application, and then I realized that our users might also need a way to send an update if necessary.

**Comment by dphiffer** [comment]
Yeah, I _think_ that should work as advertised. Maybe with two caveats.

First, every time I stand up an instance I fuss with the `synced_folder`s, which has some tricky consequences on file permissions in the VM. Take a look at the comments in the Vagrantfile for more guidance.

Secondly—and this is less about the VM than it is about Boundary Issues itself—the authentication mechanism is tightly coupled with the Mapzen OAuth system (itself relying on GitHub's OAuth). We should make it easy to switch it to use plain vanilla GitHub OAuth.

Of course, I'll be very curious to hear what trips you up along the way, since I've become too familiarized with the setup process to have any good sense for what the fragile parts are.

**Comment by thisisaaronland** [comment]
For neighbourhoods and geometries this blog post (and the pointer to the tutorial) is a good place to start:

https://mapzen.com/blog/sf-neighbourhood-updates/

Boundary Issues itself currently has little in the way of sophisticated editing tools for geometries because that gets in to a lot of complex UI/UX work and we decided to start with the only slightly-less complex UI/UX work of managing properties.

**Comment by stepps00** [comment]
Hey @davidbarratt  - as mentioned above, we published a blog about updating neighbourhood records in Who's On First. This blog also links to the longer [neighbourhood update tutorial](https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/issue_workflows/sf_neighbourhood_updates_pt_1.md), which outlines the steps required to update neighbourhood records in Who's On First.

We typically track these updates (and data-related issues) in the [whosonfirst-data](https://github.com/whosonfirst-data/whosonfirst-data/issues) repository, so if you'd like, I can file a new issue for your locality - in what area/locality were you noticing the wonky neighbourhood shapes?

**Comment by davidbarratt** [comment]
@stepps00,

I live on Idaho Woods Ln. in Orlando, FL. Somehow it says I'm in Southchase:
https://whosonfirst.mapzen.com/spelunker/id/85935139/

All of streets ending in "Woods" are part of the Meadow Woods neighborhood within the Meadow Woods census designated place (CDP). There are businesses and maybe some other neighborhoods with the CDP, but we either live in the Meadow Woods neighborhood or we don't live in an neighborhood at all, just the CDP. Regardless, we don't live in Southchase. :)

**Comment by stepps00** [comment]
@davidbarratt thanks for the info. 

Just so I'm clear, it looks like the Southchase you linked (https://whosonfirst.mapzen.com/spelunker/id/85935139/) is actually the correct **locality**... the South Chase you're falling under is the South Chase **neighbourhood** (https://whosonfirst.mapzen.com/spelunker/id/85935139/). The locality records look correct, but the neighbourhood records do not.

Either way, I've gone ahead and opened an issue in our `whosonfirst-data` repo ([here](https://github.com/whosonfirst-data/whosonfirst-data/issues/506)) to upgrade neighbourhoods in Orlando. Feel free to keep an eye on that issue and let me know if I've missed something. Thanks again!

**Comment by davidbarratt** [comment]
@stepps00,

Whoops, sorry wrong link. You're correct. and thanks for opening the issue!

**Comment by thisisaaronland** [comment]
Closing this, for now.
