### ISSUE TITLE
Hierarchy links not loading record

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-boundaryissues#254]
Certain links in the "Hierarchy" section of some records do not load, and instead load the "What?" page. It seems like this is only affecting links to newer features.

**Steps to reproduce:**

1. Go to the record for [Fiorella](https://whosonfirst.mapzen.com/boundaryissues/id/1108955983#16/37.7836/-122.4799)
2. Click on the "Macrohood: Richmond District `1108830805`" link in the Hierarchy section

The other links do work in this feature's hierarchy which makes me think that either 10-digit `wof:id` values are not being loaded correctly or Boundary Issues does not know about newer features.

**Comment by dphiffer** [comment]
This is a useful use case, but unfortunately it's something more nuanced than the `wof:id` length. (At least I _think_ so.) Basically I need to write the part that updates BI's repos in response to WOF changes landing in GitHub.

It's been a while since I've thought about this, but I'm pretty sure it was on the list of things. Something something `updated` something `go-webhookd`.

cc: @thisisaaronland

**Comment by stepps00** [comment]
This specific case for Fiorella seems to be fixed. I've checked the hierarchy of the record linked above and the "Macrohood: Richmond District `1108830805`" record now loads. 

I've also spot-checked newly updated admin records (example: [Holiday Park](https://whosonfirst.mapzen.com/boundaryissues/id/1126114159#15/52.1106/-106.6882)) and they all load as expected in Boundary Issues.

@dphiffer - are new records indexed in BI on a regular basis? If not, is a new issue needed to ensure that BI has the most recently added records in WOF?

(cc @thisisaaronland)

**Comment by dphiffer** [comment]
That is something I've been meaning to do, @stepps00, please do make an issue for it! Thanks.

**Comment by thisisaaronland** [comment]
Closing in favour of issue #301
