### ISSUE TITLE
Build / setup Gearmand hooks

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#60]
See also: issue #58

**Comment by thisisaaronland** [comment]
Assigning to you (@dphiffer) since it sounds like you got to this first. Can you add notes explaining what the what is?

**Comment by dphiffer** [comment]
Sure thing. The idea is that sometimes an action that has a simple interface (i.e., "update these 20 records") has quite a few sub-tasks, some of which may take longer to complete than the user wants to wait around for.

I just [committed](https://github.com/whosonfirst/whosonfirst-www-boundaryissues/commit/8a24c986b3415fcd029e0c4a7eabe972950e2e5a) the first set of updates that takes care of the [task handoff](https://github.com/whosonfirst/whosonfirst-www-boundaryissues/blob/8a24c986b3415fcd029e0c4a7eabe972950e2e5a/www/include/lib_wof_save.php#L89-L99) to Gearman. That in turn gets executed by [worker code](https://github.com/whosonfirst/whosonfirst-www-boundaryissues/blob/8a24c986b3415fcd029e0c4a7eabe972950e2e5a/bin/gearman_worker.php) that runs in the background.

The next time we update the Sky Box, we'll need to make sure there are Gearman workers running, so that those incoming tasks don't fall on deaf ears. That's the part I am working on next.

**Comment by dphiffer** [comment]
Some additional thoughts on more system-level Gearmand stuff, one week later:
- Move gearman_worker.php to the `services` folder
- Create a Supervisor config that gets symlinked into `/etc/supervisor/conf.d`

**Comment by thisisaaronland** [comment]
Yes to the `supervisor.d` stuff and no to the `gearman_worker.php` stuff for two reasons:
1. It is application/Flamework specific code and I'd like to keep it all in a single known place (www, include or bin)
2. Path nonsense for include files; the `bin` directory already introduces an annoying level of complexity (see `bin/init_local.php`) and I don't want to add any other rules, conditions, exceptions.

**Comment by dphiffer** [comment]
Cool, I'll leave the worker in bin.
