### ISSUE TITLE
Validate incoming EDTF values

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst/whosonfirst-www-boundaryissues#74]
Perhaps we just run it through `strtotime` and replace the result?

**Comment by thisisaaronland** [comment]
The only issue with this, and it's kind of non-trivial for a lot of places, is that `strtotime` won't work before January 1, 1970.

**Comment by dphiffer** [comment]
Oh right. Unless we have some magic date parsing beans, maybe this isn't worth solving.

See also: https://52.91.189.86/id/286327885/

**Comment by thisisaaronland** [comment]
I was quite fond of Mozilla's "brick" calendar widget and used it in privatesquare to good effect:

https://github.com/straup/privatesquare/blob/7f3cc96c8d24a03d302d720de430f512001dc9ec/www/templates/inc_user_trip_edit.txt#L22-L24

It appears to have been abandoned, since then:

http://brick.mozilla.io/

https://developer.mozilla.org/en-US/docs/Archive/Apps/Tools_and_frameworks/Web_components <-- "
Archive of obsolete content"

The simplest dumbest thing is a standard calendar widget which some notion of granularity (year, month, day) but even that feels like quicksand right now.

We should simply add an on change event handler that runs values through this:

https://github.com/nicompte/edtfy

And prints a warning if the text fails to parse. It might fail because not-EDTF or not-supported-EDTF-level.

**Comment by thisisaaronland** [comment]
Closing for now. Not an issue, yet.
